// <auto-generated />
using System;
using MailingSystem.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MailingSystem.Migrations.MailsDb
{
    [DbContext(typeof(MailsDbContext))]
    [Migration("20221130062028_SendMailInstanceEntity")]
    partial class SendMailInstanceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MailingSystem.Entities.OrganizationMail", b =>
                {
                    b.Property<int>("MailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MailId"));

                    b.Property<DateTime>("DateOfLastEmailSent")
                        .HasColumnType("datetime2");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfEmailsSent")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserVerificatiorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserWhoAdded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MailId");

                    b.ToTable("OrganizationMails");
                });

            modelBuilder.Entity("MailingSystem.Entities.SentMail", b =>
                {
                    b.Property<int>("SentMailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SentMailId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfDelivery")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizationMailInstanceMailId")
                        .HasColumnType("int");

                    b.Property<string>("SenderMailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SentMailId");

                    b.HasIndex("OrganizationMailInstanceMailId");

                    b.ToTable("SentMails");
                });

            modelBuilder.Entity("MailingSystem.Entities.SentMail", b =>
                {
                    b.HasOne("MailingSystem.Entities.OrganizationMail", "OrganizationMailInstance")
                        .WithMany("SentMails")
                        .HasForeignKey("OrganizationMailInstanceMailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationMailInstance");
                });

            modelBuilder.Entity("MailingSystem.Entities.OrganizationMail", b =>
                {
                    b.Navigation("SentMails");
                });
#pragma warning restore 612, 618
        }
    }
}
